---
abstract: 'Run CGI script from Mojolicious'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-CGI
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.00
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-cgi/issues
  homepage: https://metacpan.org/module/Mojolicious::Plugin::CGI
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojolicious-plugin-cgi
version: 0.09
