---
abstract: 'Run CGI script from Mojolicious'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-CGI
no_index:
  directory:
    - t
    - inc
requires:
  IO::Pipely: 0.005
  Mojolicious: 4.00
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-cgi/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-cgi
  repository: https://github.com/jhthorsen/mojolicious-plugin-cgi.git
version: 0.13
